create todo components
fr0N73ND3r/creative-react pull request #1
Opened 2022-01-08 15:34 UTC by fr0N73ND3r

2022-01-08 15:38 UTC, fr0N73ND3r commented
<img width="1251" alt="Снимок экрана 2022-01-08 в 20 35 02" src="https://user-images.githubusercontent.com/96487557/148650293-23d49d74-e97b-406d-8157-f8837f7e8409.png">

2022-01-11 17:15 UTC, BubbaCat requested changes

2022-01-11 17:15 UTC, BubbaCat commented on app/src/components/todo/Summary.js
> +		const impHight = this.props.tasks.filter(task => task.important === 3)
Уровень важности задач надо в какой нибудь объект запихать, и оттуда уже получать, а то щас просто магические цифры

2022-01-11 17:15 UTC, BubbaCat commented on app/src/components/todo/TaskForm.js
> +				"title": this.state.taskTitle
Выше же получил его в переменную

2022-01-11 17:15 UTC, BubbaCat commented on app/src/components/todo/TaskManager.js
> +function byCreatedAt(a, b) {
А может в отдельный файл эту функцию и данные ниже? эту в utils, а ту в constansts

2022-01-11 17:15 UTC, BubbaCat commented on app/src/components/todo/TaskManager.js
> +		this.setState(function (state) {
Стрелочные функции не нравятся?) () =>

2022-01-11 17:15 UTC, BubbaCat commented on app/src/components/todo/TaskManager.js
> +		if (this.state.showActive) {
Лучше в отдельную функцию вынеси эту логику фильтра и сортировки

2022-01-11 17:16 UTC, BubbaCat commented on app/src/components/todo/TaskManager.js
> +		if (this.state.showActive) {
и еще let { tasks } = this.state поменять на const

2022-01-16 20:26 UTC, merged